### ISSUE TITLE
Missing dependency: json

### ISSUE THREAD

**Issue by philippnbg** [mgfcf/E-Paper-Calendar-with-iCal-sync-and-live-weather#11]
<pre><font color="#34E2E2"><b>Installing a few required packages for the E-Paper Software</b></font>
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pyowm in /usr/local/lib/python3.7/dist-packages (2.10.0)
Requirement already satisfied: requests&lt;3,&gt;=2.20.0 in /usr/lib/python3/dist-packages (from pyowm) (2.21.0)
Requirement already satisfied: geojson&lt;3,&gt;=2.3.0 in /usr/local/lib/python3.7/dist-packages (from pyowm) (2.5.0)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: ics in /usr/local/lib/python3.7/dist-packages (0.5)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from ics) (2.8.0)
Requirement already satisfied: six&gt;1.5 in /usr/lib/python3/dist-packages (from ics) (1.12.0)
Requirement already satisfied: arrow&lt;0.12,&gt;=0.11 in /usr/local/lib/python3.7/dist-packages (from ics) (0.11.0)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: feedparser in /usr/local/lib/python3.7/dist-packages (5.2.1)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (1.17.2)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting json
<font color="#CC0000">Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/json/</font>
</pre>

**Comment by mgfcf** [comment]
Hey @philippnbg ,

thanks for sharing your problem. I took a look at the installer and the json package and it seems, that it is part of the standard library already. Therefor I simply removed it and the error should be gone now. If my research is somehow wrong and the json package is not included by default, than this issue may be reopened again.

Max
