### ISSUE TITLE
Not showing any display on 7in5b_V2 display.

### ISSUE THREAD

**Issue by domsmatrix2** [mgfcf/E-Paper-Calendar-with-iCal-sync-and-live-weather#18]
I have 7.5 inch 3 color 7.5inch e-Paper HAT (B) V2. Display blank as initialization file Epd7in5b_V2Adapter.py is not available in the Calendar folder. Please update with the file Epd7in5b_V2Adapter.py . Only old version display file Epd7in5bAdapter.py  is available  and is not working on the V2 model (480x800) as the commands are different. Thanks.

**Comment by mgfcf** [comment]
Hello!

Sadly, it is not as easy as just 'adding a file' and I currently don't have the capacity to fulfill your request.

I am also not sure if I will continue this repository in the current state. Maybe I will archive it, do some small improvements over time or create a new concept from the base up. But in any case, this decision will take a while. In other words, I am not planning on adding support for the v2 display any time soon to this repository. Feel free to open a pull request yourself though.

I will close this issue for the mentioned reasons. In case someone else will spend the time to fix it, feel free to open a new issue if necessary.

Best wishes,
Max
