### ISSUE TITLE
[Feature Request] Crypto Prices

### ISSUE THREAD

**Issue by dicijr** [mgfcf/E-Paper-Calendar-with-iCal-sync-and-live-weather#4]
Anyway to implement crypto prices instead of RSS feed?

Been trying to reverse-engineering it, but it hasn't been easy. Any guidance?

**Comment by mgfcf** [comment]
Currently, only the title of a RSS post is printed in a line, preceded by a dot. If you know any source that provides the desired information in such a format, where everything important is mentioned in the title, you could simply add those to the rss_feeds. That is probably not the case.
To help you, I need to know how and what information should be presented (Name of the currency, current value, maybe the latest change?) and what the source looks like. Are there some RSS-Feed similiar links? Should an additional python package be used?
I don't know much about the stock market, currrencies and all of that, but I imagine that stock and currency are related enough, so that they can be merged together into one feature somehow?

**Comment by dicijr** [comment]
I'm not a python dev, but I have some webdev skills. I understand the theory, its just the whole adapting to someone elses code is a little hard for me but I'm sure we can work together here!

https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=USD

Heres an example of an API pull from coingecko. Perhaps we could find a source that has both stocks and crypto but coingecko provides a free API (w/o token) if you can help me develop into something..

https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,litecoin&vs_currencies=USD

would be both btc and ltc

**Comment by mgfcf** [comment]
That looks great! Thanks for your research! I will work on this asap, which basically means tomorrow :D

To give some more insight into my code:
Every information (except datetime) comes from a specific class. Weather comes from OwmForecast, RSS Feeds from RssParserPosts and Events from IcalEvents. But everyone of those "data classes" inherits from an abstract data class (OwmForecast => WeatherInterface, IcalEvents => CalendarInterface, ...) and they all inherit from the abstract DataSourceInterface class (CalendarInterface => DataSourceInterface).
For the currencies that would make something like GeckoCurrency => CurrencyInterface => DataSourceInterface to provide all the functionality needed.
But you don't need to implement it that technically. You could, if you want, create one general class/collection of functions/function that collects all necessary data and transforms it into an according data object.
Every type of information is packed into its own data object class, to use data in a coherent manner. Weather is transported in a WeatherForecast object, RSS-Posts are transported in a RssPost object and events are transported in a CalendarEvent object.

Later on, every panel (a whole, finished design) needs to have somekind of function to take those information/data objects. The PanelDesign class is the basis of every design and defines the interface. A function like "add_currency" would be needed.

As you can see, I probably overcomplexified it a little bit, but on the other hand it is easier to add new things without disrupting the rest of the code. I am planning to refactor that system a little bit to make it cleaner and reduce duplicated code.

I will have a closer look tomorrow and feel free to explore the code and implement new features.

**Comment by dicijr** [comment]
I'm getting somewhere, I think I set up all the code up properly (maybe). But it seems now I can't seem to figure out what makes something is_available=true

**Comment by dicijr** [comment]
Defintely got somewhere. Just need to get the prices to display one row, instead of like this:

$8
$8
$.
$4
$7

**Comment by mgfcf** [comment]
To display information in rows or just one row, you should use the TableDesign. Simply create a matrix in the format:
```
[  COL v
    [ cell, cell, cell ],   <= ROW
    [ cell, cell, cell ]
]
```
In the constructor of TableDesign you can set a variety of design options like the alignment of the content, font size and color for each cell. These information are passed to the parameter `cell_properties` which receives a matrix in the form of the content-matrix, but each cell is replaced with a dictionary that describes each parameter of the cell:
```
default_props = {
    "color" : colors["fg"],
    "background_color" : colors["bg"],
    "font-size" : defaultfontsize
}
```
If no dictionary is given, these default values are used.
Alignment settings are passed over to `column_horizontal_alignments` as a list with the length of the amount of columns and texts, describing the horizontal alignment ("left", "center", "right") for each column.

**Comment by dicijr** [comment]
I definitely got some progress. The code definitely isn't beautiful or stable... but might need your help on some of this.

**Comment by mgfcf** [comment]
I would like to help :D Could you push your files to your fork or share them somehow?

**Comment by dicijr** [comment]
I'll upload them now. I'll sort of try to brief you i nthe commit

**Comment by dicijr** [comment]
2 sep commits, one has my comment. Have fun!
